# Generated by Django 3.2.7 on 2021-10-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('birth_date', models.DateField()),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=16)),
                ('gen', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('leave_time', models.IntegerField(default=160)),
                ('manager', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='departments.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
